name: build_publish_bis
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for release'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: clone repo
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: builder
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}
